name: Single Instance Tests

on: [push]

jobs:
  mongodb-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2]

    name: Start MongoDB Server v${{ matrix.mongodb-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install

      - run: npm test ./test/single-instance-with-configurations.js
        env:
          CI: true
